### ISSUE TITLE
Select song

### ISSUE THREAD

**Issue by TagorePde** [cycyrild/SpotifyDL#2]
Can we have a select , apart from the select all?
im having some issues to download some songs, and i want to retry.
also a timeout would be nice.
so he can continue with the rest , and make a list for the retry one. / the one that he cannot download in first instance )

**Comment by cycyrild** [comment]
> Can we have a select , apart from the select all?
> 
> im having some issues to download some songs, and i want to retry.
> 
> also a timeout would be nice.
> 
> so he can continue with the rest , and make a list for the retry one. / the one that he cannot download in first instance )

Hi normally you can start downloading a single title by simply clicking on it.
For the timeout and to ensure that download failures are not blocking, getPlayPlay license already has a retry system. Also normally if an exception occurs during downloading or conversion, in theory it does not block other pending titles, the title changes color and becomes red to signal an error.

Surely the error you have comes from somewhere else. Maybe a conversion error with ffmpeg?

Tell me more so I can correct it.

Best regards

**Comment by TagorePde** [comment]
Hi, thanks for the answer.
i m just downloading a list with 366 files, some songs fails, and at the end hang till i close it ( next day ) was hang from yesterday y the same songs.
can share here the playlist for example?
i will try again today

**Comment by cycyrild** [comment]
I think it might be due to a request limit on the Spotify API. I could try to persist the download state of a playlist with the tracks that failed so that they can be retried.
In order for me to be sure about the nature of the error you are facing, could you send me the message that appears in the devtools console of the extension popup?
Also, were you able to download individual tracks ?

**Comment by cycyrild** [comment]
I would like the playlist links too to reproduce the error.
